
class LiabilityModel {

  constructor(litresProduced, isImporter, isCopacker, litresCopacked) {
    this.litresProduced = litresProduced;
    this.isImporter = isImporter;
    this.isCopacker = isCopacker;
    this.litresCopacked = litresCopacked;
  }

  outcome() {
    if (this.litresProduced + this.litresCopacked >= 1000000) {
      return "outcome.mandatory";
    } else if (!this.isImporter &&  !this.isCopacker && this.litresCopacked != 0) {
      return "outcome.voluntary";
    } else if (this.litresCopacked == 0) {
      return "outcome.noliability.smallproducer";
    } else {
      return "outcome.mandatory-voluntary";
    }
  }

  negate(key, bool) {
    if (bool) {
      return "" + key;
    } else {
      return "no" + key;
    }
  }

  size(key, litres) {
    if (litres === 0) {
      return key + "-none";
    } else if (litres <= 1000000) {
      return key + "-small";
    } else {
      return key + "-large";
    }
  }

  messageKey() {
    if (this.outcome() === "noliability.smallproducer") {
      return this.outcome();
    } else if (this.litresProduced > 0 && this.litresCopacked > 0 && this.outcome() === "mandatory") {
      return this.outcome() + "." + this.negate("import", this.isImporter) + "." + this.negate("copackFor", this.isCopacker);
    } else {
      return this.outcome() + "." + this.size("prod", this.litresProduced) + "." + this.negate("import", this.isImporter) + "." + this.negate("copackFor", this.isCopacker) + "." + this.size("copackBy", this.litresCopacked);
    }
  }

  heading() {
    return messages.get(outcome());
  }

  text() {
    return messages.get(this.messageKey());
  }
}


var messages = new Map();


messages.set("outcome.noliability", "You do not need to register");
messages.set("outcome.mandatory", "You need to register");
messages.set("outcome.voluntary", "You can register voluntarily");
messages.set("outcome.mandatory-voluntary", "You need to register");
messages.set("outcome.noliability.smallproducer", "<p>Based on your answers you do not need to register.</p><p>You will not need to register unless you start:</p><ul class=\"list list-bullet\"><li>packaging, or having packaged on your behalf, one million litres of liable drink per year or more</li><li>packaging liable drink for a customer</li><li>bringing liable drinks into the UK</li></ul>");
messages.set("outcome.voluntary.prod-small.noimport.nocopackFor.copackBy-small", "<p>Based on your answers you do not need to register but you can register voluntarily.</p><p>If you''re registered you will not need to pay for the liable drink you package or have packaged by third parties in the UK.</p><p>If you''re not registered your third party packagers will need to pay for the liable drink they package on your behalf.</p><p>You''ll need to tell HMRC about any changes to your activity. For example, if you start:</p><ul class=\"list list-bullet\"><li>packaging, or having packaged on your behalf, one million litres of liable drink per year or more for your own brand or brands you have the rights to manufacture</li><li>packaging liable drink for a customer</li><li>bringing liable drinks into the UK</li></ul>");
messages.set("outcome.mandatory.prod-small.noimport.copackFor.copackBy-none", "<p>Based on your answers you must register, submit quarterly returns and pay for the liable drink you package for your customers.</p><p>You will not have to pay for the liable drink you package for your own brand or brands you have the rights to manufacture.</p><p>You''ll need to tell HMRC about any changes to your activity. For example, if you start:</p><ul class=\"list list-bullet\"><li>packaging, or having packaged on your behalf, one million litres of liable drink per year or more for your own brand or brands you have the rights to manufacture</li><li>bringing liable drinks into the UK</li></ul>");
messages.set("outcome.mandatory-voluntary.prod-small.noimport.copackFor.copackBy-small", "<p>Based on your answers you must register, submit quarterly returns and pay for the liable drink you package for your customers.</p><p>You will not have to pay for liable drink you package or have packaged by a third party in the UK for your own brand or brands you have the rights to manufacture.</p><p>You''ll need to tell HMRC about any changes to your activity. For example, if you start:</p><ul class=\"list list-bullet\"><li>packaging, or having packaged on your behalf, one million litres of liable drink per year or more for your own brand or brands you have the rights to manufacture</li><li>bringing liable drinks into the UK</li></ul>");
messages.set("outcome.mandatory.prod-small.import.nocopackFor.copackBy-none", "<p>Based on your answers you must register, submit quarterly returns and pay for the liable drinks you bring into the UK.</p><p>You will not have to pay for the liable drink you package for your own brand or brands you have the rights to manufacture.</p><p>You''ll need to tell HMRC about any changes to your activity. For example, if you start:</p><ul class=\"list list-bullet\"><li>packaging, or having packaged on your behalf, one million litres of liable drink per year or more for your own brand or brands you have the rights to manufacture</li><li>packaging liable drink for a customer</li></ul>");
messages.set("outcome.mandatory-voluntary.prod-small.import.nocopackFor.copackBy-small", "<p>Based on your answers you must register, submit quarterly returns and pay for the liable drinks you bring into the UK.</p><p>You will not have to pay for the liable drink you package or have packaged by third parties in the UK for your own brand or brands you have the rights to manufacture.</p><p>You''ll need to tell HMRC about any changes to your activity. For example, if you start:</p><ul class=\"list list-bullet\"><li>packaging, or having packaged on your behalf, one million litres of liable drink per year or more for your own brand or brands you have the rights to manufacture</li><li>packaging liable drink for a customer</li></ul>");
messages.set("outcome.mandatory.prod-small.import.copackFor.copackBy-none", "<p>Based on your answers you must register, submit quarterly returns and pay for the liable drink you:</p><ul class=\"list list-bullet\"><li>package for your customers</li><li>bring into the UK</li></ul><p>You will not have to pay for the liable drink you package for your own brand or brands you have the rights to manufacture.</p><p>You''ll need to tell HMRC about any changes to your activity. For example, if you start packaging, or having packaged on your behalf, one million litres of liable drink per year or more for your own brand or brands you have the rights to manufacture.</p>");
messages.set("outcome.mandatory-voluntary.prod-small.import.copackFor.copackBy-small", "<p>Based on your answers you must register, submit quarterly returns and pay for the liable drink you:</p><ul class=\"list list-bullet\"><li>package for your customers</li><li>bring into the UK</li></ul><p>You will not have to pay for the liable drink you package or have packaged by third parties in the UK for your own brand or brands you have the rights to manufacture.</p><p>You''ll need to tell HMRC about any changes to your activity. For example if you start packaging, or having packaged on your behalf, one million litres of liable drink per year or more, for your own brand or brands you have the rights to manufacture.</p>");
messages.set("outcome.mandatory.prod-large.noimport.nocopackFor.copackBy-none", "<p>Based on your answers you must register, submit quarterly returns and pay because you package one million litres of liable drink per year or more.</p><p>You''ll need to tell HMRC about any changes to your activity. For example, if you start:</p><ul class=\"list list-bullet\"><li>packaging, or having packaged on your behalf, less than one million litres of liable drink per year for your own brand or brands you have the rights to manufacture</li><li>packaging liable drink for a customer</li><li>bringing liable drinks into the UK</li></ul>");
messages.set("outcome.mandatory.noimport.nocopackFor", "<p>Based on your answers you must register, submit quarterly returns and pay for the liable drink you package for your own brand or brands you have the rights to manufacture.</p><p>You will not have to pay for the liable drink you have packaged by third parties for your own brand or brands you have the rights to manufacture.</p><p>You''ll need to tell HMRC about any changes to your activity. For example, if you start:</p><ul class=\"list list-bullet\"><li>packaging, or having packaged on your behalf, less than one million litres of liable drink per year for your own brand or brands you have the rights to manufacture</li><li>packaging liable drink for a customer</li><li>bringing liable drinks into the UK</li></ul>");
messages.set("outcome.mandatory.noimport.copackFor", "<p>Based on your answers you must register, submit quarterly returns and pay for the liable drink you:</p><ul class=\"list list-bullet\"><li>package for your own brand or brands you have the rights to manufacture</li><li>package for your customers</li></ul><p>You will not have to pay for the liable drink you have packaged by third parties for your own brand or brands you have the rights to manufacture.</p><p>You''ll need to tell HMRC about any changes to your activity. For example, if you start:</p><ul class=\"list list-bullet\"><li>packaging, or having packaged on your behalf, less than one million litres of liable drink per year for your own brand or brands you have the rights to manufacture</li><li>bringing liable drinks into the UK</li></ul>");
messages.set("outcome.mandatory.import.nocopackFor", "<p>Based on your answers you must register, submit quarterly returns and pay for the liable drink you:</p><ul class=\"list list-bullet\"><li>package for your own brand or brands you have the rights to manufacture</li><li>bring into the UK</li></ul><p>You will not have to pay for the liable drink you have packaged by third parties for your own brand or brands you have the rights to manufacture.</p><p>You''ll need to tell HMRC about any changes to your activity. For example, if you start:</p><ul class=\"list list-bullet\"><li>packaging, or having packaged on your behalf, less than one million litres of liable drink per year for your own brand or brands you have the rights to manufacture</li><li>packaging liable drink for a customer</li></ul>");
messages.set("outcome.mandatory.import.copackFor", "<p>Based on your answers you must register, submit quarterly returns and pay for the liable drink you:</p><ul class=\"list list-bullet\"><li>package for your own brand or brands you have the rights to manufacture</li><li>package for your customers</li><li>bring into the UK</li></ul><p>You will not have to pay for the liable drink you have packaged by third parties for your own brand or brands you have the rights to manufacture.</p><p>You''ll need to tell HMRC about any changes to your activity. For example if you start packaging, or having packaged on your behalf, less than one million litres of liable drink per year for your own brand or brands you have the rights to manufacture.</p>");
messages.set("outcome.mandatory.prod-none.noimport.copackFor.copackBy-none", "<p>Based on your answers you must register, submit quarterly returns and pay for the liable drink you package for your customers.</p><p>You''ll need to tell HMRC about any changes to your activity. For example, if you start:</p><ul class=\"list list-bullet\"><li>packaging, or having packaged on your behalf, liable drink for your own brand or brands you own the rights to manufacture</li><li>bringing liable drinks into the UK</li></ul>");
messages.set("outcome.mandatory.prod-none.import.nocopackFor.copackBy-none", "<p>Based on your answers you must register, submit quarterly returns and pay for the liable drink you bring into the UK.</p><p>You''ll need to tell HMRC about any changes to your activity.</p>");
messages.set("outcome.mandatory.prod-none.import.copackFor.copackBy-none", "<p>Based on your answers you must register, submit quarterly returns and pay for the liable drink you:</p><ul class=\"list list-bullet\"><li>package for your customers</li><li>bring into the UK</li></ul><p>You''ll need to tell HMRC about any changes to your activity. For example, if you start:</p><ul class=\"list list-bullet\"><li>packaging liable drink for your own brand or brands you own the rights to manufacture</li><li>using a third party to package liable drinks on your behalf</li></ul>");
messages.set("outcome.voluntary.prod-none.noimport.nocopackFor.copackBy-small", "<p>Based on your answers you do not need to register but you can register voluntarily.</p><p>If you''re registered you will not need to pay for the liable drink you have packaged by third parties in the UK.</p><p>If you''re not registered your third party packagers will need to pay for the liable drink they package on your behalf.</p><p>You''ll need to tell HMRC about any changes to your activity. For example, if you start:</p><ul class=\"list list-bullet\"><li>packaging, or having packaged on your behalf, one million litres of liable drink per year or more for your own brand or brands you have the rights to manufacture</li><li>packaging liable drink at a site you operate</li><li>packaging liable drink for a customer</li><li>bringing liable drinks into the UK</li></ul>");
messages.set("outcome.mandatory-voluntary.prod-none.noimport.copackFor.copackBy-small", "<p>Based on your answers you must register, submit quarterly returns and pay for the liable drink you package for your customers.</p><p>You will not have to pay for the liable drink you have packaged by third parties for your own brand or brands you have the rights to manufacture.</p><p>You''ll need to tell HMRC about any changes to your activity. For example, if you start:</p><ul class=\"list list-bullet\"><li>packaging, or having packaged on your behalf, one million litres of liable drink per year or more for your own brand or brands you have the rights to manufacture</li><li>bringing liable drinks into the UK</li></ul>");
messages.set("outcome.mandatory-voluntary.prod-none.import.nocopackFor.copackBy-small", "<p>Based on your answers you must register, submit quarterly returns and pay for the liable drinks you bring into the UK.</p><p>You will not have to pay for the liable drink you have packaged by third parties for your own brand or brands you have the rights to manufacture.</p><p>You''ll need to tell HMRC about any changes to your activity. For example, if you start:</p><ul class=\"list list-bullet\"><li>packaging, or having packaged on your behalf, one million litres of liable drink per year or more for your own brand or brands you have the rights to manufacture</li><li>packaging liable drinks for a customer</li></ul>");
messages.set("outcome.mandatory-voluntary.prod-none.import.copackFor.copackBy-small", "<p>Based on your answers you must register, submit quarterly returns and pay for the liable drink you:</p><ul class=\"list list-bullet\"><li>package for your customers</li><li>bring into the UK</li></ul><p>You will not have to pay for the liable drink you have packaged by third parties for your own brand or brands you have the rights to manufacture.</p><p>You''ll need to tell HMRC about any changes to your activity. For example if you start packaging, or having packaged on your behalf, one million litres of liable drink per year or more for your own brand or brands you have the rights to manufacture.</p>");
messages.set("outcome.mandatory.prod-none.noimport.nocopackFor.copackBy-large", "<p>Based on your answers you must register, but you will not need to submit quarterly returns or pay.</p><p>You''ll need to tell HMRC about any changes to your activity. For example, if you start:</p><ul class=\"list list-bullet\"><li>packaging, or having packaged on your behalf, less than one million litres of liable drink per year for your own brand or brands you have the rights to manufacture</li><li>packaging liable drinks at a site you operate</li><li>packaging liable drinks for a customer</li><li>bringing liable drinks into the UK</li></ul>");
messages.set("outcome.mandatory.prod-none.noimport.copackFor.copackBy-large", "<p>Based on your answers you must register, submit quarterly returns and pay for the liable drink you package for your customers.</p><p>You will not have to pay for the liable drink you have packaged by third parties for your own brand or brands you have the rights to manufacture.</p><p>You''ll need to tell HMRC about any changes to your activity. For example, if you start:</p><ul class=\"list list-bullet\"><li>packaging, or having packaged on your behalf, one million litres of liable drink per year or more for your own brand or brands you have the rights to manufacture</li><li>bringing liable drink into the UK</li></ul>");
messages.set("outcome.mandatory.prod-none.import.nocopackFor.copackBy-large", "<p>Based on your answers you must register, submit quarterly returns and pay for the liable drink you bring into the UK.</p><p>You will not have to pay for the liable drink you have packaged by third parties for your own brand or brands you have the rights to manufacture.</p><p>You''ll need to tell HMRC about any changes to your activity. For example, if you start:</p><ul class=\"list list-bullet\"><li>packaging, or having packaged on your behalf, less than one million litres of liable drink per year for your own brand or brands you have the rights to manufacture</li><li>packaging liable drinks for a customer</li></ul>");
messages.set("outcome.mandatory.prod-none.import.copackFor.copackBy-large", "<p>Based on your answers you must register, submit quarterly returns and pay for the liable drink you:</p><ul class=\"list list-bullet\"><li>package for your customers</li><li>bring into the UK</li></ul><p>You will not have to pay for the liable drink you have packaged by third parties for you own brand or brands you have the rights to manufacture.</p><p>You''ll need to tell HMRC about any changes to your activity. For example, if you start packaging, or having packaged on your behalf, one million litres of liable drink per year or more for your own brand or brands you have the rights to manufacture.</p>");
messages.set("outcome.mandatory.prod-large.import.nocopackFor.copackBy-none", "<p>Based on your answers you must register, submit quarterly returns and pay for the liable drink you:</p><ul class=\"list list-bullet\"><li>package for your own brand or brands you have the rights to manufacture</li><li>bring into the UK</li></ul><p>You''ll need to tell HMRC about any changes to your activity. For example, if you start:</p><ul class=\"list list-bullet\"><li>packaging, or having packaged on your behalf, less than one million litres of liable drink per year for your own brand or brands you have the rights to manufacture</li><li>using a third party to package liable drinks on your behalf</li></ul>");
messages.set("outcome.mandatory.prod-large.noimport.copackFor.copackBy-none", "<p>Based on your answers you must register, submit quarterly returns and pay for the liable drink you:</p><ul class=\"list list-bullet\"><li>package for your own brand or brands you have the rights to manufacture</li><li>package for your customers</li></ul><p>You''ll need to tell HMRC about any changes to your activity. For example, if you start:</p><ul class=\"list list-bullet\"><li>packaging, or having packaged on your behalf, less than one million litres of liable drink per year for your own brand or brands you have the rights to manufacture</li><li>bringing liable drinks into the UK</li></ul>");
messages.set("outcome.mandatory.prod-large.import.copackFor.copackBy-none", "<p>Based on your answers you must register, submit quarterly returns and pay for the liable drink you:</p><ul class=\"list list-bullet\"><li>package for your own brand or brands you have the rights to manufacture</li><li>package for your customers</li><li>bring into the UK</li></ul><p>You''ll need to tell HMRC about any changes to your activity. For example, if you start packaging, or having packaged on your behalf, less than one million litres of liable drink per year for your own brand or brands you have the rights to manufacture.</p>");


// var lm = new LiabilityModel(100000,true,true,2)
// lm.result()
